version:  2

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf